# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pxe-server-config
data:
  dnsmasq.conf: |
    interface={{ .Values.config.interface }}
    bind-interfaces
    port=0
    # 0.0.0.0 is dummy IP address that is needed to meet dnsmasq syntax requirements.
    # The line below is used to turn dnsmasq into ProxyDHCP mode. 
    dhcp-range=0.0.0.0,proxy
    
    leasefile-ro
    no-hosts
    log-dhcp
    log-queries
    log-facility=-
    log-debug
    enable-tftp
    tftp-root=/var/lib/tftp

    dhcp-match=set:pxe,60,PXEClient
    dhcp-match=set:efi64,option:client-arch,7

    pxe-service=tag:pxe,tag:efi64,x86-64_EFI,"Network Boot UEFI x86_64",ipxe.efi,{{ .Values.config.bootServer }}
