# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

CI 🤖:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

root:
  - changed-files:
      - any-glob-to-any-file: "*"

infra-core:
  - changed-files:
    - any-glob-to-any-file:
      - "infra-core/**"
      - "api/**"
      - "exporter/**"
      - "inventory/**"
      - "credentials/**"
      - "tenant-controller/**"

infra-external:
  - changed-files:
    - any-glob-to-any-file:
      - "infra-external/**"
      - "loca-manager/**"
      - "loca-credentials/**"
      - "loca-metadata-manager/**"
      - "loca-templates-manager/**"

infra-manager:
  - changed-files:
    - any-glob-to-any-file:
      - "infra-manager/**"
      - "host-manager/**"
      - "maintenance-manager/**"
      - "networking-manager/**"
      - "telemetry-manager/**"
      - "os-resource-manager/**"
      - "attestationstatus-manager/**"

infra-onboarding:
  - changed-files:
    - any-glob-to-any-file:
      - "infra-onboarding/**"
      - "onboarding-manager/**"
      - "dkam/**"
      - "tinkerbell/**"
      - "infra-config/**"
