---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "amt-{{ include "rps.fullname" . }}-kyverno-restart"
  namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "amt-{{ include "rps.fullname" . }}-kyverno-restart"
subjects:
- kind: ServiceAccount
  name: "kyverno-background-controller"
  namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "amt-{{ include "rps.fullname" . }}-kyverno-restart"
  namespace: kyverno
rules:
- apiGroups: ["apps"]
  resources: ["deployment"]
  verbs: ["create", "get","update", "list", "watch"]
