# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tftp-server.fullname" . }}
  labels:
    {{- include "tftp-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tftp-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tftp-server.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # init container is used to prepare mounted ipxe.efi to be served with tftp-secure option.
      # tftp-secure assumes that file permissions must be the same as user running inside the Pod.
      # Otherwise, PXE server rejects the PXE clients' requests.
      # This init container mounts the global PV, copies the ipxe.efi to a dedicated location with
      # allowed file permissions.
      initContainers:
        - name: tftp-permissions
          image: busybox:1.36.1
          command: [ "/bin/sh" ]
          args: [ "-c", "cp /tmp/ipxe.efi /tftp-storage && chmod 640 /tftp-storage/ipxe.efi && chown 65534:65534 /tftp-storage/ipxe.efi" ]
          volumeMounts:
            {{- if .Values.standaloneMode.enabled }}
            - name: local-path
              mountPath: "/tmp/ipxe.efi"
            {{- else }}
            - name: nginx-pvc
              mountPath: "/tmp/ipxe.efi"
              subPath: "signed_ipxe.efi"
            {{- end }}
            - name: tftp-storage
              mountPath: /tftp-storage
          securityContext:
            {{- toYaml .Values.initContainerSecurityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: dnsmasq-pid-directory
              mountPath: /var/run/eim-dnsmasq
            - name: config
              mountPath: /etc/dnsmasq.conf
              subPath: dnsmasq.conf
            - name: tftp-storage
              mountPath: /var/lib/tftp/ipxe.efi
              subPath: ipxe.efi
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - "in.tftpd"
            - "--listen"
            - "-vv"
            - "--address"
            - ":6969"
            - "--secure"
            - "/var/lib/tftp"
      volumes:
        - name: tftp-storage
          emptyDir: {}
        - name: dnsmasq-pid-directory
          emptyDir: {}
        - name: config
          configMap:
            name: tftp-server-config
        {{- if .Values.standaloneMode.enabled }}
        - name: local-path
          hostPath:
            path: "{{- required "standaloneMode.ipxePath is mandatory!" .Values.standaloneMode.ipxePath }}"
            type: File
        {{- else }}
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.claimName }}"
        {{- end }}
