# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

{{- if .Values.traefikReverseProxy.enabled }}
# UDP IngressRoute
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: "{{ .Values.ingress.name }}"
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  entryPoints:
    - tftp-server  # must match a UDP entryPoint defined in Traefik static config
  routes:
    - services:
        - name: {{ include "tftp-server.fullname" . }}
          port: {{ .Values.service.port }}
          namespace: {{ .Release.Namespace }}
{{- end }}
