# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "tftp-server.fullname" . }}
  labels:
    {{- include "tftp-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      name: tftp-port
      protocol: UDP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "rps.selectorLabels" . | nindent 4 }}
