# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: inventory
description: Edge Infrastructure Manager Inventory
type: application
version: 2.25.0
appVersion: "2.27.0"
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
