# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mps-middleware-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "authMiddleware.js" "multiTenancyMiddleware.js" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}
  
