# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.job.secretjob.configmap }}"
  namespace: orch-infra
data:
  db-script.sh: |
    #!/bin/bash

    # To postgres secret from orch-database namespace
    SECRET_VALUE_MPS=$(kubectl get secret mps-local-postgresql -n orch-infra -o jsonpath="{.data.PGPASSWORD}" | base64 --decode)
    SECRET_VALUE_RPS=$(kubectl get secret rps-local-postgresql -n orch-infra -o jsonpath="{.data.PGPASSWORD}" | base64 --decode)

    # Create connection strings for mps, mps-router, and rps
    connection_string_mps="postgresql://orch-infra-mps_user:$SECRET_VALUE_MPS@postgresql.orch-database/orch-infra-mps?sslmode=disable"
    connection_string_rps="postgresql://orch-infra-rps_user:$SECRET_VALUE_RPS@postgresql.orch-database/orch-infra-rps?sslmode=disable"

    # Output the connection strings for verification
    echo "Connection String (MPS): $connection_string_mps"
    echo "Connection String (RPS): $connection_string_rps"

    # Create Kubernetes secrets with the connection strings
    kubectl create secret generic mps --from-literal=connectionString="$connection_string_mps" -n orch-infra
    kubectl create secret generic rps --from-literal=connectionString="$connection_string_rps" -n orch-infra

