# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.job.secretjob.name }}"
  namespace: orch-infra
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: "{{ .Values.rbac.serviceaccount }}"
      containers:
      - name: db-password-secret
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c", "cp /scripts/db-script.sh /test/db-script.sh && chmod +x /test/db-script.sh && /test/db-script.sh"]
        volumeMounts:
        - name: cm-vol
          mountPath: /scripts
        - name: exec-volume
          mountPath: /test
      restartPolicy: Never
      volumes:
      - name: cm-vol
        configMap:
          name: "{{ .Values.job.secretjob.configmap }}"
      - name: exec-volume
        emptyDir: {}
