# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel

apiVersion: v2
name: mps
description: Edge Infrastructure Manager AMT MPS
type: application
version: 0.0.1
appVersion: "0.0.1"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
