# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: infra-onboarding
description: Edge Infrastructure Manager Onboarding Umbrella Chart
type: application
version: "1.27.0"
appVersion: "1.27.0"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
dependencies:
  - name: onboarding-manager
    condition: import.onboarding-manager.enabled
    version: "1.34.0"
    repository: "file://../onboarding-manager"
  - name: dkam
    condition: import.dkam.enabled
    version: "1.24.0"
    repository: "file://../dkam"
  - name: tinkerbell
    condition: import.tinkerbell.enabled
    version: "2.10.0"
    repository: "file://../tinkerbell"
  - name: infra-config
    condition: import.infra-config.enabled
    version: "0.5.1"
    repository: "file://../infra-config"
  - name: amt
    condition: import.amt.enabled
    version: "0.0.1"
    repository: "file://../amt"
