# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel

{{- if .Values.traefikReverseProxy.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Values.ingress.name }}"
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: "Host(`{{ .Values.traefikReverseProxy.host.grpc.name }}`) && PathPrefix(`/`)"
    kind: Rule
    middlewares:
       - name: validate-jwt
    services:
      - name: {{ include "mpsrouter.fullname" . }}
        port: {{ .Values.service.port }}
        scheme: h2c
        namespace: {{ .Release.Namespace }}
  tls:
    secretName: {{ .Values.traefikReverseProxy.secretName }}
{{- if .Values.traefikReverseProxy.tlsOption }}
    options:
      name: {{ .Values.traefikReverseProxy.tlsOption }}
      namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
{{- end }}
{{- end }}
