# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel

# Default values for AMT/MPS ROUTER.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
global:
  registry:
    name: null
    imagePullSecrets:
      - name: ""

replicaCount: 1

image:
  repository: intel/oact-mpsrouter
  tag: latest
  pullPolicy: IfNotPresent


nameOverride: ""
fullnameOverride: "mpsrouter"


podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: "8003"
  mpsport: "3000"

ingress:
  name: "amt-api-mpsrouter"

traefikReverseProxy:
  host:
    grpc:
      name: ""
  dnsname: 
  # -- enabled is a switch to turn on/off the Traefik reverse proxy resource; Traefik MUST be deployed to gateway-system ns before enabling it here.
  enabled: false
  # -- gatewayNamespace specifies namespace of Traefik and related resources (e.g. k8s secret or tls option).
  gatewayNamespace: orch-gateway
  # -- secretName is name of k8s secret containing TLS server cert.
  secretName:  tls-demo
  # -- matchRoute defines routing rules (e.g. Host(`http.sample.com`))
  matchRoute:
  # -- tlsOption is the name of the Traefik option for handling TLS or mTLS connections.
  tlsOption: gateway-tls


podAnnotations: {}

imagePullSecrets: {}

nodeSelector: {}

tolerations: []

affinity: {}
