# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

global:
  registry:
    name: null
    imagePullSecrets:
      - name: ""

mps:
  name: mps
  enabled: true
  service:
    enabled: true
    type: ClusterIP
  image:
    repository: intel/oact-mps
    tag: latest
    pullPolicy: IfNotPresent
    # Image specific takes precedence
    # registry:
    #   name: null
    #   imagePullSecrets:
    #     - name: ""

rps:
  name: rps
  enabled: true
  service:
    enabled: true
    type: ClusterIP
  image:
    repository: intel/oact-rps
    tag: latest
    pullPolicy: IfNotPresent
    # Image specific takes precedence
    # registry:
    #   name: null
    #   imagePullSecrets:
    #     - name: ""
