# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

global:
  registry:
    name: null
    imagePullSecrets:
      - name: ""

import:
  mps:
    enabled: true
  rps:
    enabled: true

mps:
  image:
    repository: intel/oact-mps
    tag: latest
    pullPolicy: IfNotPresent
    # Image specific takes precedence
    # registry:
    #   name: null
    #   imagePullSecrets:
    #     - name: ""

rps:
  image:
    repository: intel/oact-rps
    tag: latest
    pullPolicy: IfNotPresent
    # Image specific takes precedence
    # registry:
    #   name: null
    #   imagePullSecrets:
    #     - name: ""
